[package]
name = "hnotes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-rc.3"
tokio = { version = "1.16.1", features = ["macros", "rt-multi-thread"] }
