services:
  app:
    build: .
    ports:
      - '127.0.0.1:8080:80'

  db:
    image: docker.io/library/mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: hnotes
      MYSQL_DATABASE: hbombch_hutter
      MYSQL_USER: hbombch_notes
      MYSQL_PASSWORD: xxx
    volumes:
      - "db-data:/var/lib/mysql"

volumes:
  db-data: {}
